---

- name: Configure httpd for {{ vhost.servername }}
  debug:
    var: vhost
    verbosity: 2

- name: Create SSL directories
  include_tasks: ssl.yml
  when: vhost.with_ssl | default(false) | bool

- name: Configure vhost for {{ vhost.servername }}
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ vhost.servername }}.conf
    owner: root
    group: root
    mode: 0644
  register: conf

- name: Enable vhost for {{ vhost.servername }}
  command: "a2ensite {{ vhost.servername }}"
  notify: Restart httpd
  when: conf.changed
