---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: apache-ubuntu-20-04-$TOX_ENVNAME
    groups: [ "apache" ]
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    # create: ../.playbooks/create.yml
    converge: ../.playbooks/playbook.yml
    # destroy: ../.playbooks/destroy.yml
  inventory:
    links:
      group_vars: ../.inventory/group_vars/
  lint:
    name: ansible-lint
scenario:
  name: default_docker
verifier:
  name: testinfra
  directory: ../.tests/
  lint:
    name: flake8
