---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-focal-$TOX_ENVNAME
    alias: ubuntu/20.04/amd64
    groups: [ "apache" ]
    image: docker.io/ubuntu:focal
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    links:
      group_vars: ../.inventory/group_vars/
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../.tests/
  lint:
    name: flake8
